const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));let S={user:null,cats:[],tags:[]};
async function api(p,o={}){let r=await fetch(p,{headers:{'content-type':'application/json',...(o.headers||{})},...o}),d=await r.json();if(!r.ok)throw Error(d.error||'Ошибка');return d}
function toast(x){let t=$('#toast');t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function modal(h){$('#box').innerHTML=h;$('#modal').classList.remove('hidden')}function close(){ $('#modal').classList.add('hidden') }
$('#modal').onclick=e=>{if(e.target.classList.contains('shade')||e.target.id==='x')close()};
async function base(){let [m,c,t]=await Promise.all([api('/api/me'),api('/api/categories'),api('/api/tags')]);S.user=m.user;S.cats=c.categories;S.tags=t.tags;$('#login').textContent=S.user?S.user.username:'Войти';$('#admin').classList.toggle('hidden',S.user?.role!=='admin');$('#cats').innerHTML='<button data-cat="0">Все статьи</button>'+S.cats.map(c=>`<button class="${c.parent_id?'sub':''}" data-cat="${c.id}">${c.parent_id?'↳ ':''}${esc(c.name)}</button>`).join('');$('#tags').innerHTML=S.tags.slice(0,18).map(t=>`<button class="tag" data-tag="${esc(t.name)}">#${esc(t.name)}</button>`).join('')}
$('#cats').onclick=e=>{let b=e.target.closest('[data-cat]');if(b)location.hash=b.dataset.cat==='0'?'#/':'#/category/'+b.dataset.cat};$('#tags').onclick=e=>{let b=e.target.closest('[data-tag]');if(b){$('#q').value=b.dataset.tag;go()}};function go(){let q=$('#q').value.trim();location.hash=q?'#/search/'+encodeURIComponent(q):'#/'}$('#go').onclick=go;$('#q').onkeydown=e=>{if(e.key==='Enter')go()};$('#login').onclick=()=>S.user?logout():auth();$('#admin').onclick=()=>location.hash='#/admin';
async function logout(){await api('/api/logout',{method:'POST'});await base();location.hash='#/';toast('Вы вышли')}
function auth(){modal(`<button id="x" class="close">×</button><h2>Войти</h2><form id="f" class="form"><div class="field"><label>Логин</label><input name="username" required></div><div class="field"><label>Пароль</label><input name="password" type="password" required></div><div class="actions"><button type="button" id="reg">Регистрация</button><button class="accent">Войти</button></div></form>`);$('#f').onsubmit=async e=>{e.preventDefault();try{await api('/api/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});close();await base();toast('Вход выполнен')}catch(x){toast(x.message)}};$('#reg').onclick=reg}
function reg(){modal(`<button id="x" class="close">×</button><h2>Регистрация</h2><form id="f" class="form"><div class="field"><label>Логин</label><input name="username" required></div><div class="field"><label>Пароль</label><input name="password" type="password" minlength="6" required></div><div class="actions"><button type="button" id="back">Назад</button><button class="accent">Создать</button></div></form>`);$('#f').onsubmit=async e=>{e.preventDefault();try{await api('/api/register',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});toast('Аккаунт создан');auth()}catch(x){toast(x.message)}};$('#back').onclick=auth}
const cards=a=>`<article class="article card"><div class="meta">${esc(a.category_name||'Без категории')} · ${new Date(a.updated_at).toLocaleDateString('ru-RU')}</div><h3><a href="#/article/${a.id}">${esc(a.title)}</a></h3><p>${esc(a.excerpt||'Открыть статью…')}</p><div class="chips">${(a.tags||[]).map(t=>`<button class="tag" data-tag="${esc(t.name)}">#${esc(t.name)}</button>`).join('')}</div></article>`;
async function render(){let h=decodeURIComponent(location.hash),v=$('#view');if(h.startsWith('#/article/')){let a=(await api('/api/article/'+h.split('/')[2])).article;v.innerHTML=`<article class="article-page card"><button onclick="history.back()">← Назад</button><div class="meta">${esc(a.category_name||'Статья')} · ${esc(a.author||'')}</div><h1>${esc(a.title)}</h1><div class="chips">${(a.tags||[]).map(t=>`<button class="tag" data-tag="${esc(t.name)}">#${esc(t.name)}</button>`).join('')}</div><div class="article-body">${esc(a.content)}</div>${S.user?.role==='admin'?`<div class="actions"><button class="accent" onclick="edit(${a.id})">Редактировать</button></div>`:''}</article>`;return}
if(h==='#/admin'){return admin()}let q='',cat='';if(h.startsWith('#/search/'))q=h.split('/').slice(2).join('/');if(h.startsWith('#/category/'))cat=h.split('/')[2];let url='/api/articles?'+(q?'q='+encodeURIComponent(q):'')+(cat?'&category='+cat:'');let d=await api(url),title=q?`Поиск: «${esc(q)}»`:cat?esc(S.cats.find(c=>c.id==cat)?.name||'Категория'):'Последние статьи';v.innerHTML=`<div class="head"><div><div class="meta">ВОЗНЕСЕНИЕ WIKI</div><h2>${title}</h2></div>${S.user?.role==='admin'?'<button class="accent" onclick="edit()">+ Статья</button>':''}</div>${d.articles.length?'<div class="grid">'+d.articles.map(cards).join('')+'</div>':'<div class="empty card"><b>Пока пусто</b>Добавь первую статью через админку.</div>'}`}
async function edit(id){let a=id?(await api('/api/article/'+id)).article:{title:'',excerpt:'',content:'',category_id:'',tags:[]};modal(`<button id="x" class="close">×</button><h2>${id?'Изменить статью':'Новая статья'}</h2><form id="f" class="form"><div class="field"><label>Название</label><input name="title" value="${esc(a.title)}" required></div><div class="row"><div class="field"><label>Категория</label><select name="category_id"><option value="">Без категории</option>${S.cats.map(c=>`<option value="${c.id}" ${c.id==a.category_id?'selected':''}>${c.parent_id?'↳ ':''}${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Теги через запятую</label><input name="tags" value="${esc((a.tags||[]).map(t=>t.name).join(', '))}" placeholder="магия, война, королевство"></div></div><div class="field"><label>Описание</label><input name="excerpt" value="${esc(a.excerpt)}"></div><div class="field"><label>Текст</label><textarea name="content" required>${esc(a.content)}</textarea></div><div class="actions"><button type="button" id="x">Отмена</button><button class="accent">Сохранить</button></div></form>`);$('#f').onsubmit=async e=>{e.preventDefault();let b=Object.fromEntries(new FormData(e.target));b.tags=b.tags.split(',').map(x=>x.trim()).filter(Boolean);try{await api(id?'/api/articles/'+id:'/api/articles',{method:id?'PUT':'POST',body:JSON.stringify(b)});close();toast('Статья сохранена');await render()}catch(x){toast(x.message)}}}
async function admin(){if(S.user?.role!=='admin'){toast('Нужны права администратора');return location.hash='#/'}$('#view').innerHTML=`<div class="head"><div><div class="meta">УПРАВЛЕНИЕ</div><h2>Админ-панель</h2></div><button class="accent" onclick="edit()">+ Статья</button></div><div class="card" style="padding:15px"><div class="actions" style="justify-content:flex-start"><button onclick="alist()">Статьи</button><button onclick="clist()">Категории</button><button onclick="ulist()">Пользователи</button></div><div id="panel"></div></div>`;alist()}
async function alist(){let d=await api('/api/articles');$('#panel').innerHTML='<div class="list">'+(d.articles.length?d.articles.map(a=>`<div class="item"><div><b>${esc(a.title)}</b><small>${(a.tags||[]).map(t=>'#'+esc(t.name)).join(' ')}</small></div><div><button onclick="edit(${a.id})">Изменить</button> <button class="danger" onclick="delA(${a.id})">Удалить</button></div></div>`).join(''):'<div class="empty">Нет статей.</div>')+'</div>'}
async function delA(id){if(confirm('Удалить статью?')){await api('/api/articles/'+id,{method:'DELETE'});alist();toast('Удалено')}}
async function clist(){$('#panel').innerHTML=`<div class="actions" style="justify-content:space-between"><b>Категории</b><button class="accent" onclick="newcat()">+ Категория</button></div><div class="list">${S.cats.map(c=>`<div class="item"><span>${c.parent_id?'↳ ':''}${esc(c.name)}</span><button class="danger" onclick="delC(${c.id})">Удалить</button></div>`).join('')}</div>`}function newcat(){modal(`<button id="x" class="close">×</button><h2>Новая категория</h2><form id="f" class="form"><div class="field"><label>Название</label><input name="name" required></div><div class="field"><label>Родитель</label><select name="parent_id"><option value="">Нет</option>${S.cats.filter(c=>!c.parent_id).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="actions"><button type="button" id="x">Отмена</button><button class="accent">Создать</button></div></form>`);$('#f').onsubmit=async e=>{e.preventDefault();await api('/api/categories',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});close();await base();clist();toast('Создано')}}async function delC(id){if(confirm('Удалить категорию?')){await api('/api/categories/'+id,{method:'DELETE'});await base();clist()}}
async function ulist(){let d=await api('/api/users');$('#panel').innerHTML='<div class="list">'+d.users.map(u=>`<div class="item"><div><b>${esc(u.username)}</b><small>${u.role==='admin'?'Администратор':'Пользователь'} · ${u.disabled?'заблокирован':'активен'}</small></div><div>${u.id!==S.user.id?`<button onclick="role(${u.id},'${u.role==='admin'?'user':'admin'}')">${u.role==='admin'?'Снять админку':'Сделать админом'}</button> <button onclick="block(${u.id},${!u.disabled})">${u.disabled?'Разблокировать':'Заблокировать'}</button> <button class="danger" onclick="delU(${u.id})">Удалить</button>`:''}</div></div>`).join('')+'</div>'}async function role(id,r){await api('/api/users/'+id,{method:'PATCH',body:JSON.stringify({role:r})});ulist()}async function block(id,x){await api('/api/users/'+id,{method:'PATCH',body:JSON.stringify({disabled:x})});ulist()}async function delU(id){if(confirm('Удалить пользователя?')){await api('/api/users/'+id,{method:'DELETE'});ulist()}}
window.addEventListener('hashchange',render);(async()=>{try{await base();await render()}catch(e){$('#view').innerHTML='<div class="card empty">D1 пока не подключена. Выполни шаги из README.md.</div>'}})();
