const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));let S={user:null,cats:[],tags:[],articles:[]};
async function api(p,o={}){let r=await fetch(p,{...o,headers:{...(o.body instanceof FormData?{}:{'content-type':'application/json'}),...(o.headers||{})}}),d=await r.json();if(!r.ok)throw Error(d.error||'Ошибка');return d}
function toast(x){let t=$('#toast');t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}function modal(h){$('#box').innerHTML=h;$('#modal').classList.remove('hidden')}function close(){ $('#modal').classList.add('hidden') }$('#modal').onclick=e=>{if(e.target.classList.contains('shade')||e.target.id==='x')close()};
async function base(){let[m,c,t]=await Promise.all([api('/api/me'),api('/api/categories'),api('/api/tags')]);S.user=m.user;S.cats=c.categories.filter(x=>x.slug!=='karta-mira'&&x.name!=='Карта мира');S.tags=t.tags;$('#login').textContent=S.user?S.user.username:'Войти';$('#admin').classList.toggle('hidden',S.user?.role!=='admin');$('#cats').innerHTML='<button data-cat="0">Все статьи</button>'+S.cats.map(c=>'<button class="'+(c.parent_id?'sub':'')+'" data-cat="'+c.id+'">'+(c.parent_id?'↳ ':'')+esc(c.name)+'</button>').join('');}
$('#cats').onclick=e=>{let b=e.target.closest('[data-cat]');if(b)location.hash=b.dataset.cat==='0'?'#/':'#/category/'+b.dataset.cat};function go(){let q=$('#q').value.trim();location.hash=q?'#/search/'+encodeURIComponent(q):'#/'}$('#go').onclick=go;$('#q').onkeydown=e=>{if(e.key==='Enter')go()};$('#login').onclick=()=>S.user?logout():auth();$('#admin').onclick=()=>location.hash='#/admin';
async function logout(){await api('/api/logout',{method:'POST'});await base();location.hash='#/';toast('Вы вышли')}function auth(){modal('<button id="x">×</button><h2>Войти</h2><form id="f" class="form"><div class="field"><label>Логин</label><input name="username" required></div><div class="field"><label>Пароль</label><input name="password" type="password" required></div><div class="actions"><button type="button" id="reg">Регистрация</button><button class="accent">Войти</button></div></form>');$('#f').onsubmit=async e=>{e.preventDefault();try{await api('/api/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});close();await base();toast('Вход выполнен')}catch(x){toast(x.message)}};$('#reg').onclick=reg}function reg(){modal('<button id="x">×</button><h2>Регистрация</h2><form id="f" class="form"><div class="field"><label>Логин</label><input name="username" required></div><div class="field"><label>Пароль</label><input name="password" type="password" minlength="6" required></div><div class="actions"><button type="button" id="back">Назад</button><button class="accent">Создать</button></div></form>');$('#f').onsubmit=async e=>{e.preventDefault();try{await api('/api/register',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});toast('Аккаунт создан');auth()}catch(x){toast(x.message)}};$('#back').onclick=auth}
const cards=a=>'<article class="article card">'+(a.cover_id?'<img class="article-cover" src="/api/image/'+a.cover_id+'">':'')+'<div class="meta">'+esc(a.category_name||'Без категории')+'</div><h3><a href="#/article/'+a.id+'">'+esc(a.title)+'</a></h3><p>'+esc(a.excerpt||'Открыть статью…')+'</p></article>';
async function home(){const icons={'Персонажи':'👤','Локации':'🌍','Лор':'📖','Организации':'🏛️','События':'⚔️','Игроки':'👥'};const cats=S.cats.filter(c=>!c.parent_id);$('#home-extra').innerHTML='<div class="home-wrap"><div class="section-title"><h2>Разделы мира</h2><span>Исследуйте энциклопедию</span></div><div class="catalog-grid">'+cats.map(c=>'<a class="catalog card" href="#/category/'+c.id+'"><div class="ico">'+(icons[c.name]||'◈')+'</div><h3>'+esc(c.name)+'</h3><p>Открыть раздел →</p></a>').join('')+'<a class="catalog card" href="#/timeline"><div class="ico">📜</div><h3>Хронология</h3><p>Открыть раздел →</p></a><a class="catalog card" href="#/tags"><div class="ico">🏷️</div><h3>Теги</h3><p>Открыть раздел →</p></a></div></div>';}
async function render(){let h=decodeURIComponent(location.hash||'#/'),v=$('#view'),homeMode=(h==='#/'||h==='');document.body.classList.toggle('route-only',!homeMode);if(homeMode){await home();let d=await api('/api/articles?limit=6');v.innerHTML='<div class="head"><div><div class="meta">НОВЫЕ МАТЕРИАЛЫ</div><h2>Последние статьи</h2></div>'+(S.user?.role==='admin'?'<button class="accent" onclick="edit()">+ Статья</button>':'')+'</div>'+(d.articles.length?'<div class="grid">'+d.articles.map(cards).join('')+'</div>':'<div class="empty card"><b>Wiki готова к наполнению</b>Администратор может создать первые статьи.</div>');return}if(h.startsWith('#/article/'))return article(+h.split('/')[2]);if(h==='#/admin')return admin();if(h==='#/timeline')return timeline();if(h==='#/tags')return tagsPage();if(h.startsWith('#/search/'))return listing('Поиск: «'+esc(h.split('/').slice(2).join('/'))+'»','/api/articles?q='+encodeURIComponent(h.split('/').slice(2).join('/')));if(h.startsWith('#/tag/'))return listing('Тег: #'+esc(h.split('/').slice(2).join('/')),'/api/articles?tag='+encodeURIComponent(h.split('/').slice(2).join('/')));if(h.startsWith('#/category/')){let id=h.split('/')[2],c=S.cats.find(x=>x.id==id);return listing(esc(c?.name||'Категория'),'/api/articles?category='+id)}return listing('Раздел','/api/articles')}
async function tagsPage(){let v=$('#view');v.innerHTML='<div class="head"><div><div class="meta">НАВИГАЦИЯ</div><h2>🏷️ Теги</h2><p class="muted">Выберите тег, чтобы увидеть связанные статьи.</p></div></div><div class="tag-cloud">'+(S.tags.length?S.tags.map(t=>'<a class="tag tag-link" href="#/tag/'+encodeURIComponent(t.name)+'">#'+esc(t.name)+' <small>'+t.count+'</small></a>').join(''):'<div class="empty card">Тегов пока нет.</div>')+'</div>'}
async function listing(title,url){let d=await api(url),v=$('#view');v.innerHTML='<div class="head"><div><div class="meta">ВОЗНЕСЕНИЕ WIKI</div><h2>'+title+'</h2></div>'+(S.user?.role==='admin'?'<button class="accent" onclick="edit()">+ Статья</button>':'')+'</div>'+(d.articles.length?'<div class="grid">'+d.articles.map(cards).join('')+'</div>':'<div class="empty card"><b>Ничего не найдено</b>Попробуйте другой запрос или создайте статью.</div>')}
async function article(id){let d=await api('/api/article/'+id),a=d.article,v=$('#view');v.innerHTML='<article class="article-page card"><div class="meta">'+esc(a.category_name||'Статья')+' · '+esc(a.author||'')+'</div><div class="article-top"><div><h1>'+esc(a.title)+'</h1>'+((a.images||[]).map(im=>'<img class="article-image" src="/api/image/'+im.id+'" alt="'+esc(im.filename||a.title)+'">').join(''))+'<div class="article-body">'+esc(a.content)+'</div></div></div><div class="relations"><h3>Связи</h3><div class="rel-grid">'+((a.relations||[]).map(r=>'<a class="rel" href="#/article/'+r.id+'"><small>'+esc(r.label||'Связано с')+'</small><b>'+esc(r.title)+'</b></a>').join('')||'<span class="muted">Связанных статей пока нет.</span>')+'</div></div><div class="related"><h3>Читайте также</h3><div class="rel-grid">'+((a.related||[]).map(r=>'<a class="rel" href="#/article/'+r.id+'"><b>'+esc(r.title)+'</b></a>').join('')||'<span class="muted">Пока нет рекомендаций.</span>')+'</div></div>'+(S.user?.role==='admin'?'<div class="actions"><button onclick="edit('+a.id+')">Редактировать</button><button onclick="manageImages('+a.id+')">Фотографии</button></div>':'')+'</article>'}
async function timeline(){let d=await api('/api/timeline'),v=$('#view');v.innerHTML='<div class="head"><div><div class="meta">ИСТОРИЯ МИРА</div><h2>📜 Хронология</h2></div></div><div class="timeline">'+(d.years.map(y=>'<div class="year">'+esc(y.year)+'</div>'+y.items.map(x=>'<div class="event"><a href="#/article/'+x.id+'"><b>'+esc(x.title)+'</b></a><div class="muted">'+esc(x.excerpt||'')+'</div></div>').join('')).join('')||'<div class="empty card">Пока нет событий.</div>')+'</div>'}
async function edit(id){
  if(S.user?.role!=='admin'){toast('Требуются права администратора.');return}
  let a=null;
  if(id){a=(await api('/api/article/'+id)).article}
  if(!S.articles.length){try{S.articles=(await api('/api/articles?limit=200')).articles}catch{S.articles=[]}}
  const cats=S.cats.filter(c=>!c.parent_id||c.parent_id);
  const opts=S.cats.map(c=>'<option value="'+c.id+'" '+((a?.category_id==c.id)?'selected':'')+'>'+((c.parent_id?'↳ ':'')+esc(c.name))+'</option>').join('');
  const selected=(a?.tags||[]).map(t=>t.name).join(', ');
  const rels=(a?.relations||[]).map(r=>({id:r.id,label:r.label}));
  const relRows=rels.map(r=>'<div class="relation-row"><select name="rid"><option value="'+r.id+'" selected>'+esc((S.articles.find(x=>x.id==r.id)||{}).title||r.title||('Статья #'+r.id))+'</option></select><input name="rl" value="'+esc(r.label||'Связано с')+'"><button type="button" onclick="this.parentElement.remove()">×</button></div>').join('');
  modal('<button id="x">×</button><h2>'+(id?'Редактировать статью':'Новая статья')+'</h2><form id="articleForm" class="form">'+
    '<div class="field"><label>Название</label><input name="title" required maxlength="180" value="'+esc(a?.title||'')+'"></div>'+ 
    '<div class="row"><div class="field"><label>Категория</label><select name="category_id"><option value="">Без категории</option>'+opts+'</select></div><div class="field"><label>Год / дата для хронологии</label><input name="year" value="'+esc(a?.year||'')+'" placeholder="Например: 2025"></div></div>'+ 
    '<div class="field"><label>Краткое описание</label><textarea name="excerpt" style="min-height:90px">'+esc(a?.excerpt||'')+'</textarea></div>'+ 
    '<div class="field"><label>Текст статьи</label><textarea name="content" required>'+esc(a?.content||'')+'</textarea></div>'+ 
    '<div class="field"><label>Теги</label><input name="tags" value="'+esc(selected)+'" placeholder="персонаж, Вознесение, фракция"></div>'+ 
    '<div class="field"><label>Связи</label><div id="rel-editor">'+relRows+'</div><button type="button" onclick="addRel()">+ Добавить связь</button></div>'+ 
    '<div class="field"><label>Фотография</label><input name="cover" type="file" accept="image/jpeg,image/png,image/webp"><small class="muted">Можно добавить фото сразу после сохранения. До 1,9 МБ.</small></div>'+ 
    '<div class="actions"><button type="button" id="cancelEdit">Отмена</button><button class="accent">'+(id?'Сохранить изменения':'Создать статью')+'</button></div></form>');
  // Populate relation selectors with all articles after the initial selected rows.
  const form=$('#articleForm');
  if(S.articles.length){form.querySelectorAll('select[name="rid"]').forEach(sel=>{const current=sel.value;sel.innerHTML='<option value="">Выберите статью</option>'+S.articles.filter(x=>x.id!=id).map(x=>'<option value="'+x.id+'" '+(x.id==current?'selected':'')+'>'+esc(x.title)+'</option>').join('')})}
  $('#cancelEdit').onclick=close;
  form.onsubmit=async e=>{
    e.preventDefault();
    const fd=new FormData(form), rel=[];
    form.querySelectorAll('.relation-row').forEach(row=>{const rid=row.querySelector('[name="rid"]')?.value;if(rid)rel.push({id:+rid,label:row.querySelector('[name="rl"]')?.value||'Связано с'})});
    const payload={title:fd.get('title'),excerpt:fd.get('excerpt'),content:fd.get('content'),category_id:fd.get('category_id')?+fd.get('category_id'):null,year:fd.get('year')||'',kind:'article',tags:String(fd.get('tags')||'').split(',').map(x=>x.trim()).filter(Boolean),relations:rel,info:{}};
    try{
      const r=id?await api('/api/articles/'+id,{method:'PUT',body:JSON.stringify(payload)}):await api('/api/articles',{method:'POST',body:JSON.stringify(payload)});
      const newId=id||r.article.id;
      const file=fd.get('cover');
      if(file&&file.size){await uploadImage(newId,file)}
      close();
      toast(id?'Статья обновлена':'Статья создана');
      if(location.hash==='#/admin')alist();else location.hash='#/article/'+newId;
    }catch(x){toast(x.message)}
  };
}
function addRel(){let d=document.createElement('div');d.className='relation-row';d.innerHTML='<select name="rid">'+S.articles.map(a=>'<option value="'+a.id+'">'+esc(a.title)+'</option>').join('')+'</select><input name="rl" value="Связано с"><button type="button" onclick="this.parentElement.remove()">×</button>';$('#rel-editor').appendChild(d)}
async function uploadImage(id,file){if(!file.type.startsWith('image/'))return;if(file.size>1900000)throw Error('Фото слишком большое. Выбери изображение до 1,8 МБ.');let fd=new FormData();fd.append('file',file,file.name);await api('/api/articles/'+id+'/images',{method:'POST',body:fd})}async function manageImages(id){let a=(await api('/api/article/'+id)).article;modal('<button id="x">×</button><h2>Фотографии: '+esc(a.title)+'</h2><div class="upload-preview">'+(a.images||[]).map(im=>'<div><img src="/api/image/'+im.id+'"><button class="danger" onclick="delImage('+im.id+','+id+')">Удалить</button></div>').join('')+'</div><form id="uf" class="form"><input name="file" type="file" accept="image/jpeg,image/png,image/webp" required><button class="accent">Добавить фото</button></form>');$('#uf').onsubmit=async e=>{e.preventDefault();try{await uploadImage(id,e.target.file.files[0]);close();toast('Фото добавлено');render()}catch(x){toast(x.message)}}}async function delImage(i,id){if(confirm('Удалить фото?')){await api('/api/images/'+i,{method:'DELETE'});manageImages(id)}}
async function admin(){if(S.user?.role!=='admin'){location.hash='#/';return}$('#view').innerHTML='<div class="head"><div><div class="meta">УПРАВЛЕНИЕ WIKI</div><h2>Админ-панель</h2></div><button class="accent" onclick="edit()">+ Статья</button></div><div class="card panel"><div class="actions" style="justify-content:flex-start"><button onclick="alist()">Статьи</button><button onclick="clist()">Категории</button><button onclick="ulist()">Пользователи</button></div><div id="panel"></div></div>';alist()}
async function alist(){let d=await api('/api/articles?limit=200');S.articles=d.articles;$('#panel').innerHTML='<div class="list">'+(d.articles.length?d.articles.map(a=>'<div class="item"><div><b>'+esc(a.title)+'</b><small>'+(a.tags||[]).map(t=>'#'+esc(t.name)).join(' ')+'</small></div><div><button onclick="edit('+a.id+')">Изменить</button> <button class="danger" onclick="delA('+a.id+')">Удалить</button></div></div>').join(''):'<div class="empty">Нет статей.</div>')+'</div>'}async function delA(id){if(confirm('Удалить статью?')){await api('/api/articles/'+id,{method:'DELETE'});alist();toast('Удалено')}}async function clist(){$('#panel').innerHTML='<div class="actions" style="justify-content:space-between"><b>Категории</b><button class="accent" onclick="newcat()">+ Категория</button></div><div class="list">'+S.cats.map(c=>'<div class="item"><span>'+(c.parent_id?'↳ ':'')+esc(c.name)+'</span><button class="danger" onclick="delC('+c.id+')">Удалить</button></div>').join('')+'</div>'}function newcat(){modal('<button id="x">×</button><h2>Новая категория</h2><form id="f" class="form"><div class="field"><label>Название</label><input name="name" required></div><div class="field"><label>Родитель</label><select name="parent_id"><option value="">Нет</option>'+S.cats.filter(c=>!c.parent_id).map(c=>'<option value="'+c.id+'">'+esc(c.name)+'</option>').join('')+'</select></div><div class="actions"><button type="button" id="x">Отмена</button><button class="accent">Создать</button></div></form>');$('#f').onsubmit=async e=>{e.preventDefault();await api('/api/categories',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});close();await base();clist();toast('Создано')}}async function delC(id){if(confirm('Удалить категорию?')){await api('/api/categories/'+id,{method:'DELETE'});await base();clist()}}async function ulist(){let d=await api('/api/users');$('#panel').innerHTML='<div class="list">'+d.users.map(u=>'<div class="item"><div><b>'+esc(u.username)+'</b><small>'+(u.role==='admin'?'Администратор':'Пользователь')+' · '+(u.disabled?'заблокирован':'активен')+'</small></div><div>'+(u.id!==S.user.id?'<button onclick="role('+u.id+',\''+(u.role==='admin'?'user':'admin')+'\')">'+(u.role==='admin'?'Снять админку':'Сделать админом')+'</button> <button onclick="block('+u.id+','+(!u.disabled)+')">'+(u.disabled?'Разблокировать':'Заблокировать')+'</button> <button class="danger" onclick="delU('+u.id+')">Удалить</button>':'')+'</div></div>').join('')+'</div>'}async function role(id,r){await api('/api/users/'+id,{method:'PATCH',body:JSON.stringify({role:r})});ulist()}async function block(id,x){await api('/api/users/'+id,{method:'PATCH',body:JSON.stringify({disabled:x})});ulist()}async function delU(id){if(confirm('Удалить пользователя?')){await api('/api/users/'+id,{method:'DELETE'});ulist()}}
window.addEventListener('hashchange',render);(async()=>{try{await base();await render()}catch(e){$('#view').innerHTML='<div class="card empty"><b>Не удалось загрузить Wiki</b>'+esc(e.message)+'</div>'}})();