const CATS=[['Персонажи','personazhi'],['Локации','lokacii'],['Лор','lor'],['Игроки','igroki']];
const ADMIN='NIGHT_KING', ADMIN_PASS='vozn_04', COOKIE='voz_session';
const J=(x,s=200,h={})=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store',...h}});
const slug=s=>String(s||'').trim().toLowerCase().replace(/ё/g,'е').normalize('NFKD').replace(/[^\p{L}\p{N}]+/gu,'-').replace(/^-|-$/g,'').slice(0,90)||'item';
const token=()=>{let a=new Uint8Array(32);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,'0')).join('')};
async function sha(s){let b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function hp(p,s=token()){let k=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveBits']);let b=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(s),iterations:120000,hash:'SHA-256'},k,256);return s+':'+[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function okpass(p,h){let s=h.split(':')[0];return h===await hp(p,s)}
function ck(req){return (req.headers.get('Cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(COOKIE+'='))?.split('=')[1]}
async function me(req,e){let t=ck(req);if(!t)return null;return await e.DB.prepare('SELECT u.id,u.username,u.role,u.disabled FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?').bind(await sha(t),Date.now()).first()}
async function init(e){for(let [n,s] of CATS)await e.DB.prepare('INSERT OR IGNORE INTO categories(name,slug) VALUES(?,?)').bind(n,s).run();let u=await e.DB.prepare('SELECT id FROM users WHERE username=?').bind(ADMIN).first();if(!u)await e.DB.prepare('INSERT INTO users(username,password_hash,role) VALUES(?,?,?)').bind(ADMIN,await hp(ADMIN_PASS),'admin').run()}
async function tags(e,id){return (await e.DB.prepare('SELECT t.name,t.slug FROM tags t JOIN article_tags x ON x.tag_id=t.id WHERE x.article_id=? ORDER BY t.name').bind(id).all()).results}
async function full(e,id){let a=await e.DB.prepare('SELECT a.*,c.name category_name,u.username author FROM articles a LEFT JOIN categories c ON c.id=a.category_id LEFT JOIN users u ON u.id=a.author_id WHERE a.id=?').bind(id).first();if(a)a.tags=await tags(e,id);return a}
async function setTags(e,id,arr){await e.DB.prepare('DELETE FROM article_tags WHERE article_id=?').bind(id).run();for(let n of [...new Set((arr||[]).map(x=>String(x).trim()).filter(Boolean).slice(0,25))]){let s=slug(n);await e.DB.prepare('INSERT OR IGNORE INTO tags(name,slug) VALUES(?,?)').bind(n,s).run();let t=await e.DB.prepare('SELECT id FROM tags WHERE slug=?').bind(s).first();await e.DB.prepare('INSERT OR IGNORE INTO article_tags(article_id,tag_id) VALUES(?,?)').bind(id,t.id).run()}}
async function api(req,e){let u=await me(req,e),url=new URL(req.url),p=url.pathname,m=req.method;
 if(m==='GET'&&p==='/api/me')return J({user:u});
 if(m==='POST'&&p==='/api/register'){let b=await req.json(),n=String(b.username||'').trim(),pw=String(b.password||'');if(!/^[A-Za-zА-Яа-яЁё0-9_]{3,24}$/.test(n)||pw.length<6)return J({error:'Логин 3–24 символа, пароль от 6.'},400);if(await e.DB.prepare('SELECT id FROM users WHERE username=?').bind(n).first())return J({error:'Логин уже занят.'},409);await e.DB.prepare('INSERT INTO users(username,password_hash) VALUES(?,?)').bind(n,await hp(pw)).run();return J({ok:true})}
 if(m==='POST'&&p==='/api/login'){let b=await req.json(),r=await e.DB.prepare('SELECT * FROM users WHERE username=?').bind(String(b.username||'').trim()).first();if(!r||r.disabled||!(await okpass(String(b.password||''),r.password_hash)))return J({error:'Неверный логин или пароль.'},401);let t=token();await e.DB.prepare('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)').bind(await sha(t),r.id,Date.now()+2592000000).run();return J({ok:true,user:{id:r.id,username:r.username,role:r.role}},200,{'set-cookie':`${COOKIE}=${t}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000`})}
 if(m==='POST'&&p==='/api/logout'){let t=ck(req);if(t)await e.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha(t)).run();return J({ok:true},200,{'set-cookie':`${COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`})}
 if(m==='GET'&&p==='/api/categories')return J({categories:(await e.DB.prepare('SELECT * FROM categories ORDER BY parent_id IS NOT NULL,name').all()).results});
 if(m==='GET'&&p==='/api/tags')return J({tags:(await e.DB.prepare('SELECT t.name,t.slug,COUNT(x.article_id) count FROM tags t LEFT JOIN article_tags x ON x.tag_id=t.id GROUP BY t.id ORDER BY count DESC,t.name LIMIT 60').all()).results});
 if(m==='GET'&&p==='/api/articles'){let q=url.searchParams.get('q')||'',cat=+url.searchParams.get('category')||0,tag=url.searchParams.get('tag')||'',sql='SELECT DISTINCT a.id,a.title,a.slug,a.excerpt,a.category_id,a.updated_at,c.name category_name FROM articles a LEFT JOIN categories c ON c.id=a.category_id LEFT JOIN article_tags x ON x.article_id=a.id LEFT JOIN tags t ON t.id=x.tag_id WHERE 1=1',ps=[];if(q){sql+=' AND (lower(a.title) LIKE lower(?) OR lower(a.excerpt) LIKE lower(?) OR lower(a.content) LIKE lower(?) OR lower(t.name) LIKE lower(?))';let z='%'+q+'%';ps.push(z,z,z,z)}if(cat){sql+=' AND (a.category_id=? OR a.category_id IN(SELECT id FROM categories WHERE parent_id=?))';ps.push(cat,cat)}if(tag){sql+=' AND t.slug=?';ps.push(slug(tag))}sql+=' ORDER BY a.updated_at DESC LIMIT 100';let rows=(await e.DB.prepare(sql).bind(...ps).all()).results;for(let a of rows)a.tags=await tags(e,a.id);return J({articles:rows})}
 if(m==='GET'&&p.startsWith('/api/article/')){let a=await full(e,+p.split('/').pop());return a?J({article:a}):J({error:'Статья не найдена'},404)}
 if(!u||u.role!=='admin'||u.disabled)return J({error:'Требуются права администратора.'},403);
 if(m==='POST'&&p==='/api/articles'){let b=await req.json();if(!b.title)return J({error:'Название обязательно.'},400);let s=slug(b.slug||b.title);if(await e.DB.prepare('SELECT id FROM articles WHERE slug=?').bind(s).first())s+='-'+Date.now().toString().slice(-5);let r=await e.DB.prepare('INSERT INTO articles(title,slug,excerpt,content,category_id,author_id,updated_at) VALUES(?,?,?,?,?,?,CURRENT_TIMESTAMP)').bind(b.title,s,b.excerpt||'',b.content||'',b.category_id||null,u.id).run();await setTags(e,r.meta.last_row_id,b.tags);return J({article:await full(e,r.meta.last_row_id)})}
 if(m==='PUT'&&p.startsWith('/api/articles/')){let id=+p.split('/').pop(),b=await req.json();await e.DB.prepare('UPDATE articles SET title=?,slug=?,excerpt=?,content=?,category_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(b.title,slug(b.slug||b.title),b.excerpt||'',b.content||'',b.category_id||null,id).run();await setTags(e,id,b.tags);return J({article:await full(e,id)})}
 if(m==='DELETE'&&p.startsWith('/api/articles/')){await e.DB.prepare('DELETE FROM articles WHERE id=?').bind(+p.split('/').pop()).run();return J({ok:true})}
 if(m==='POST'&&p==='/api/categories'){let b=await req.json();try{await e.DB.prepare('INSERT INTO categories(name,slug,parent_id) VALUES(?,?,?)').bind(b.name,slug(b.slug||b.name),b.parent_id||null).run();return J({ok:true})}catch{return J({error:'Такая категория уже есть.'},409)}}
 if(m==='DELETE'&&p.startsWith('/api/categories/')){await e.DB.prepare('DELETE FROM categories WHERE id=?').bind(+p.split('/').pop()).run();return J({ok:true})}
 if(m==='GET'&&p==='/api/users')return J({users:(await e.DB.prepare('SELECT id,username,role,disabled,created_at FROM users ORDER BY username').all()).results});
 if(m==='PATCH'&&p.startsWith('/api/users/')){let id=+p.split('/').pop(),b=await req.json();if(id===u.id&&b.role==='user')return J({error:'Нельзя снять админку с себя.'},400);if(b.role)await e.DB.prepare('UPDATE users SET role=? WHERE id=?').bind(b.role,id).run();if(typeof b.disabled==='boolean')await e.DB.prepare('UPDATE users SET disabled=? WHERE id=?').bind(b.disabled?1:0,id).run();return J({ok:true})}
 if(m==='DELETE'&&p.startsWith('/api/users/')){let id=+p.split('/').pop();if(id===u.id)return J({error:'Нельзя удалить себя.'},400);await e.DB.prepare('DELETE FROM users WHERE id=?').bind(id).run();return J({ok:true})}
 return J({error:'Not found'},404)}
export default {async fetch(req,e){try{await init(e);let u=new URL(req.url);if(u.pathname.startsWith('/api/'))return api(req,e);if(!['/','/index.html','/app.js','/style.css'].includes(u.pathname))return new Response('Not found',{status:404});return e.ASSETS.fetch(req)}catch(x){return J({error:'Ошибка сервера',detail:x.message},500)}}};
