name = "voznesenie-wiki-nk"
main = "worker.js"
compatibility_date = "2026-08-25"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "voznesenie-wiki-db"
database_id = "dc1695af-9944-4a5d-901b-7280f540bb93"
